dependencies:
  - smartcontractkit/chainlink-brownie-contracts@0.3.0

compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@0.3.0"

networks:
  rinkeby:
    eth_usd_price_feed: "0x8A753747A1Fa494EC906cE90E9f37563A8AF630e"

accounts:
  account_0: 0x29BB88a558af48962753d2acb029A5a932535684
  account_1: 0xF430C7cff29a08f98A8590b9adD3BFaE7287858B
